logging.level.root: ERROR

spring:
  main:
    banner-mode: "off"
    web-environment: false

com:
  example:
    movierecommendations:
      rotten-potatoes:
        api-key: 5662925b-bc61-4a7e-825e-a84721697110
        url: http://localhost:8080/movies