logging:
  level:
    root: 'off'
    org:
      springframework: 'off'

spring:
  main:
    banner-mode: 'off'

com:
  jamesdschmidt:
    movierecommendations:
      rottenpotatoes:
        apikey: 34902188-32FC-4D55-B657-2EB1B7A7389F
        url: http://localhost:8080
