/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import io.vertx.core.Vertx;
import io.vertx.ext.web.client.HttpResponse;
import io.vertx.ext.web.client.WebClient;
import io.vertx.ext.web.codec.BodyCodec;

import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;

public class TimeClient {
  private static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss z MMMM d yyyy");

  public static void main(String[] args) {
    var client = WebClient.create(Vertx.vertx());
    client
        .get(8080, "localhost", "/")
        .timeout(5000)
        .as(BodyCodec.json(CurrentTime.class))
        .send(asyncResult -> {
          if (asyncResult.succeeded()) {
            HttpResponse<CurrentTime> response = asyncResult.result();
            CurrentTime currentTime = response.body();
            ZonedDateTime zonedDateTime = currentTime.getCurrentTime().atZone(ZoneId.systemDefault());
            System.out.println("The current time is " + zonedDateTime.format(formatter)  + ".");
          } else {
            System.out.println("Something went wrong " + asyncResult.cause().getMessage());
          }
        });
  }
}
