noun = input("Enter a noun: ")
verb = input("Enter a verb: ")
adjective = input("Enter an adjective: ")
adverb = input("Enter an adverb: ")
print(f"Do you {verb} your {adjective} {noun} {adverb}? That's hilarious!")
